Update NuGet.config (add source to restore MAUI NuGet packages).
dotnet/maui-samples pull request #156
Opened 2021-05-30 14:47 UTC by ncarandini

On .NET 6 preview 4 we need to add a source to restore MAUI NuGet packages.
We can do it running CLI commands:
```
dotnet new nugetconfig
dotnet nuget add source -n maui-preview https://aka.ms/maui-preview/index.json
```
Or adding the source on VS:

![image](https://user-images.githubusercontent.com/139274/120108415-519c7d80-c165-11eb-8ca5-c7e08fc90972.png)

I do prefer the second way beacause it works on any new MAUI project.
Alas it doesn't work if there is, as in the maui-samples repo, a NuGet.config file with a <clear /> comand 😢

So I've created this PR adding the needed source  to the file itself.

2021-06-01 15:16 UTC, jonathanpeppers commented on NuGet.config
>      <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
Microsoft.Maui.* should be on this feed as well. What version are are you looking for?

2021-06-01 15:17 UTC, jonathanpeppers requested changes
We're wanting to remove the `NuGet.config` file completely in the next preview, so I don't think we need this change.

I would be interested to understand why you need it, though. Thanks!

2021-06-02 05:55 UTC, ncarandini commented
Hi @jonathanpeppers, it's ia simple addition to the actual `NuGet.config` file that is needed to build, as stated in the @davidortinau blog post [Announcing .NET MAUI Preview 4 - Get Started Today](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-4/#get-started-today):

![image](https://user-images.githubusercontent.com/139274/120429721-305eab80-c376-11eb-9a2b-e75ada3ab3b8.png)

This PR is aimed to ease the experience of those who, having not read the post, want to try to download and build the examples contained in this repository just following the readme of this repo, where that step (adding the source) is not mentioned.

Maybe internally you don't have the issue, but as a simple dev in the wild, without it I have build errors.

On the next preview, when you'll delete the `NuGet.config` file, also this addition will disappear.

2021-06-02 12:35 UTC, jonathanpeppers commented on NuGet.config
>      <add key="xamarin" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json" />
Ok, LOL the new source:

https://aka.ms/maui-preview/index.json

Just redirects to:

https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json

The .NET MAUI team must have made this, I was not aware of it.

If you want to just change the above line:

```suggestion
    <add key="maui" value="https://aka.ms/maui-preview/index.json" />
```

I think we should probably use all lower case & short words for the keys, thanks!

2021-06-02 17:19 UTC, jonathanpeppers approved these changes

2021-06-02 17:21 UTC, merged